### ISSUE TITLE
Rascal connects to RabbitMQ stop receiving messages under high load

### ISSUE THREAD

**Issue by thaoula** [onebeyond/rascal#226]
Hi Team,

We have been using Rascal for a while now but we have recently started utilising RabbitMQ streams to process messages. This generally works well until you publish a large number of messages to the stream.

Under minimal load everything works fine. The workers receive and process the messages in a timely manner. 

Under high load, everything starts off ok. The workers receive and start processing the messages then at some point they appear to suddenly stop and the following is written to the console. 
{
  vhost: 'dev',
  mode: 'confirm',
  queue: 0,
  size: 5,
  available: 2,
  borrowed: 2,
  min: 1,
  max: 5
}

## Expected Behavior

Rascal is able to process all messages in the stream.

## Actual Behavior

Rascal is stopping for some reason and is not able to resume.

## Steps to Reproduce

1. Create a rabbitmq stream
2. Create several workers that connects to the Rabbitmq stream using Rascal
3. Publish (in our case) 254k messages to stream
4. Watch the workers process and suddenly stop and never recover until you restart the process.

## Context

We are trying to use RabbitMQ streams to allow various processing to occur in response to events. This works well when the amount of changes is small but fails when large amounts of events are published to the stream.

## Your Environment

* Version used: 17.0.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 20
* Operating System and version (desktop or mobile): MacOS Docker (Linux containers)
* Link to your project:

**Comment by cressie176** [comment]
Hi @thaoula,

This is most likely an issue with how the client application has been developed rather than Rascal itself. Publishing messages using a confirm channel is relatively slow, and so if you publish a high number of messages, you can create a backlog within the client application, using up resources and causing Node.js to perform badly and even hang. To resolve this, you need to design the client application to throttle the work leading to creation of new messages to match the publish throughput available in your environment. It's a similar concept to applying back pressure when using node's stream. Rascal (and the underlying ampqlib) provide some mechanisms to help, but if they have been used incorrectly, it could also cause your application to stop publishing messages. The following [example](https://github.com/onebeyond/rascal/blob/17e1773b645ed0c2c260a0779aa8b60f5f436a64/examples/busy-publisher/index.js) demonstrates how to pause and resume publication when you have a high number of messages.

Something in your application looks like it is already trying to handle this by logging the channel pool statistics (Rascal does not do this automatically, so it must be coming from somewhere in your application). Either you call logging the publication.stats object or you have attached an event listener to Rascal's [busy event](https://github.com/onebeyond/rascal/tree/17e1773b645ed0c2c260a0779aa8b60f5f436a64?tab=readme-ov-file#flow-control) and logging the context object. The output indicates that there are no requests for channels in the queue and that there are still channels available in the pool, which is odd - with so many messages I would expect the channel request queue to be very high and the pool to be fully utilised. It may be however, that the event loop was already flooded so even the requests to get a channel to the pool are effectively blocked behind the 254K publish operations.

There are other, related, but less likely reasons for the application to stop publishing messages too. It is possible that the RabbitMQ broker is running out of memory. You can detect this by listening for Rascal's [blocked event](https://github.com/onebeyond/rascal/tree/17e1773b645ed0c2c260a0779aa8b60f5f436a64?tab=readme-ov-file#blocked--unblocked)

It is also possible that because the event loop has been flooded, your application cannot send / receive the [RabbitMQ heartbeat](https://www.rabbitmq.com/heartbeats.html). In this situation the connection will be closed and Rascal will emit an 'error' event, potentially crashing your application. Since your application does not appear to be crashing, I suspect you may be handling this, and Rascal should attempt to reconnect. However, if your event loop is saturated it will not be able to.

Yet another possibility is that RabbitMQ stops confirming messages (although I have only ever seen this happen once). In this case, Rascal will wait for 10 seconds before [timing out](https://github.com/onebeyond/rascal/tree/17e1773b645ed0c2c260a0779aa8b60f5f436a64?tab=readme-ov-file#timeouts) so you should notice this, unless you are handling errors but not reporting them.

An alternative to throttling is to try tuning your application to publish messages more quickly. You can do this by [increasing the number of channels in the pool](https://github.com/onebeyond/rascal/tree/17e1773b645ed0c2c260a0779aa8b60f5f436a64?tab=readme-ov-file#channel-pooling), however since the output indicates there is capacity in the pool, I doubt this will help. What would certainly make a big difference is not using publisher confirms **providing it is safe to do so in your situation** 

A tool that may aid your investigation is [Wireshark](https://www.rabbitmq.com/amqp-wireshark.html). You can use this to see what messages are being sent / received between your applications and the RabbitMQ broker. It will reveal the point when messages stop flowing, if channels / connects are closed and if heartbeats are still sent and received.

**Comment by cressie176** [comment]
Sorry, I've just re-read and you mention using RabbitMQ streams. Do you mean by declaring a queue with the `x-queue-type` option set to `stream`? Can you link to a GitHub repo with sample code please?

**Comment by cressie176** [comment]
As an experiment I changed the busy-example config as follows...

```json
{
  "$schema": "../../lib/config/schema.json",
  "vhosts": {
    "/": {
      "publicationChannelPools": {
        "confirmPool": {
          "max": 10,
          "min": 10,
          "evictionRunIntervalMillis": 1000,
          "idleTimeoutMillis": 5000,
          "autostart": true
        }
      },
      "connection": {
        "socketOptions": {
          "timeout": 1000
        }
      },
      "exchanges": ["demo_ex"],
      "queues": {
        "demo_q": {
          "options": {
            "arguments": {
              "x-queue-type": "stream"
            }
          }
        }
      },
      "bindings": ["demo_ex[a.b.c] -> demo_q"],
      "publications": {
        "demo_pub": {
          "exchange": "demo_ex",
          "routingKey": "a.b.c",
          "confirm": true,
          "options": {
            "persistent": true
          }
        }
      },
      "subscriptions": {
        "demo_sub": {
          "queue": "demo_q"
        }
      }
    }
  }
}
```

#### Sample Output
```
1707639308589 Resuming vhost: / (mode: confirm, queue: 0, size: 10, borrowed: 5, available: 5)
1707639308591 Pausing vhost: / (mode: confirm, queue: 10, size: 10, borrowed: 10, available: 0)
1707639308602 Resuming vhost: / (mode: confirm, queue: 0, size: 10, borrowed: 8, available: 2)
1707639308603 Pausing vhost: / (mode: confirm, queue: 10, size: 10, borrowed: 10, available: 0)
1707639308611 Resuming vhost: / (mode: confirm, queue: 0, size: 10, borrowed: 9, available: 0)
1707639308612 Pausing vhost: / (mode: confirm, queue: 10, size: 10, borrowed: 10, available: 0)
1707639308625 Resuming vhost: / (mode: confirm, queue: 0, size: 10, borrowed: 6, available: 4)
1707639308627 Pausing vhost: / (mode: confirm, queue: 10, size: 10, borrowed: 10, available: 0)
1707639308636 Resuming vhost: / (mode: confirm, queue: 0, size: 10, borrowed: 8, available: 1)
1707639308638 Pausing vhost: / (mode: confirm, queue: 10, size: 10, borrowed: 10, available: 0)
1707639308647 Resuming vhost: / (mode: confirm, queue: 0, size: 10, borrowed: 8, available: 1)
1707639308649 Pausing vhost: / (mode: confirm, queue: 10, size: 10, borrowed: 10, available: 0)
1707639308656 Resuming vhost: / (mode: confirm, queue: 0, size: 10, borrowed: 9, available: 1)
1707639308658 Pausing vhost: / (mode: confirm, queue: 10, size: 10, borrowed: 10, available: 0)
1707639308668 Resuming vhost: / (mode: confirm, queue: 0, size: 10, borrowed: 6, available: 3)
1707639308670 Pausing vhost: / (mode: confirm, queue: 10, size: 10, borrowed: 10, available: 0)
1707639308677 Resuming vhost: / (mode: confirm, queue: 0, size: 10, borrowed: 9, available: 0)
1707639308679 Pausing vhost: / (mode: confirm, queue: 10, size: 10, borrowed: 10, available: 0)
1707639308691 Resuming vhost: / (mode: confirm, queue: 0, size: 10, borrowed: 7, available: 3)
1707639308694 Pausing vhost: / (mode: confirm, queue: 10, size: 10, borrowed: 10, available: 0)
```

#### RabbitMQ Management UI

<img width="1182" alt="Screenshot 2024-02-11 at 08 14 21" src="https://github.com/onebeyond/rascal/assets/229672/b83dd538-ae3e-404e-96e6-7c000f4619e8">

**Comment by cressie176** [comment]
However...

After a while longer I started receiving the following errors in the console...

```
Error: Timedout after 10000ms waiting for broker to confirm publication to: demo_ex
    at Timeout._onTimeout (/Users/steve/Development/onebeyond/rascal/lib/amqp/Publication.js:247:10)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) d7deaca5-76d5-413f-989e-1896ace5edc6
1707639750758 Resuming vhost: / (mode: confirm, queue: 0, size: 10, borrowed: 9, available: 0)
Error: Timedout after 10000ms waiting for broker to confirm publication to: demo_ex
    at Timeout._onTimeout (/Users/steve/Development/onebeyond/rascal/lib/amqp/Publication.js:247:10)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) b39c6a8a-92e1-4234-aea0-6806b0b6a80a
Error: Timedout after 10000ms waiting for broker to confirm publication to: demo_ex
    at Timeout._onTimeout (/Users/steve/Development/onebeyond/rascal/lib/amqp/Publication.js:247:10)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) 5e805fc5-2d27-41b0-b432-807f03cec4c1
Error: Timedout after 10000ms waiting for broker to confirm publication to: demo_ex
    at Timeout._onTimeout (/Users/steve/Development/onebeyond/rascal/lib/amqp/Publication.js:247:10)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) 1c44d2b0-6ab1-4f5a-b652-f2b454de10a4
```

```
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/Users/steve/Development/onebeyond/rascal/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/Users/steve/Development/onebeyond/rascal/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) f7f84564-05fb-46cb-aa49-3eedee1c592c
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/Users/steve/Development/onebeyond/rascal/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/Users/steve/Development/onebeyond/rascal/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) b5d4048e-f31f-44e7-b6a0-3237233c2822
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/Users/steve/Development/onebeyond/rascal/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/Users/steve/Development/onebeyond/rascal/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) ecae7671-a1a3-4aec-9dc6-a3ec43948c8d
```

The RabbitMQ Management UI showed publications had stopped

<img width="1273" alt="Screenshot 2024-02-11 at 08 27 23" src="https://github.com/onebeyond/rascal/assets/229672/9fa732b9-ad51-48a6-ab4b-c7e7c237b0ba">

The reasons is because the RabbitMQ container disk was full

<img width="1314" alt="Screenshot 2024-02-11 at 08 28 40" src="https://github.com/onebeyond/rascal/assets/229672/f86af5d0-aae4-480b-8a97-d8335cd54bfc">

Could this be your reason?

**Comment by cressie176** [comment]
Any update @thaoula?

**Comment by thaoula** [comment]
Hi @cressie176,

Apologies for the delay. got consumed by lunar new year week.

I am working with x-queue-type=stream. 

On the publisher side I have a MongoDB ChangeStream that is listening to changes in the database. These changes are then pushed to the the rabbitmq stream and then consumed by a number of processors. 

Since your initial post which is filled with lots of great information (thank you).

I have split the publisher and consumer into two seperate containers. The publisher and consumer were running on the same container originally. 

I am now attempting to stop the Mongodb ChangeStream during the "busy" event and start it up on the "ready" event. Not sure if this is going to work well as the events seems to be close together.

We encountered a massive issue yesterday where we had the tight CPU loop and the heartbeat issue you described above at the same time. This caused a lot of messages to replayed over and over (I believe they may have been poison due to misconfiguration)

On the consumer we have lot of async / await code and we use Prefetch=1 in an attempt to limit the number messages processed. 

The signature of on(event: "message", listener: (message: Message, content: any, ackOrNackFn: AckOrNack) => void) does not look like it is expecting a promise to be returned.  

Does each await allow Rascal to get another message off the queue?
Since everything is async does that mean we can get into CPU issues and therefore heartbeat issues?

The misconfiguration we had yesterday caused a very long delay to an email processing consumer. I believe during this delay the message could not be acknowledged and was requeued. We currently ackOrNack based on error or success at the end.  The email was sent (1000's of times). After we fixed the misconfigured email template everything straightened it self out. 

The reason I ask about the async / await is because I am also attempting to track the Stream Offset in the database so I can resume if restarted.

I am console logging out the situation where the current processed offset is less that the current stored offset. My naive belief was that this should be a rare occurrence but it happens quite a lot. Which leads me to suspect that we are talking a lot of items off the queue. Faster than they can be processed and their async nature is not returning them in a sequential manner. 

My naive assumption once again would be get message, processs, store offset .. get next messsage etc etc.. 

In really it seems to be get message A await process, get message B await process, get message C await process, get message D await  process... store offset B, store offset C, Store offset A, store offset D. 

Is the expected behaviour because of the connection pool? If so, do you have any suggestion for handling the offset tracking?

I am still looking into WireShark.

I know there is a lot of things here so many thanks for your assistance in advanced.

Regards,
Tarek

**Comment by cressie176** [comment]
Hi @thaoula 

> I have split the publisher and consumer into two seperate containers. The publisher and consumer were running on the same container originally.

This is a good improvement. One of Rascal's weaknesses is that it doesn't make it easy to use a different connection for publishers and consumers (you would need to define separate vhosts). Publishing and consuming messages on the same connection can impact performance.

> I am now attempting to stop the Mongodb ChangeStream during the "busy" event and start it up on the "ready" event. Not sure if this is going to work well as the events seems to be close together.

It should stop your application backing up messages at least. On my laptop (intel macbook) I can publish around 1,500 messages a second using the busy publisher example. However, because Rascal does publish using a shared channel, it will be slower than just using amqplib. 

> This caused a lot of messages to replayed over and over (I believe they may have been poison due to misconfiguration)

You can use Rascal's [redelivery counter](https://github.com/onebeyond/rascal#dealing-with-redeliveries) to detect and prevent this

> The signature of on(event: "message", listener: (message: Message, content: any, ackOrNackFn: AckOrNack) => void) does not look like it is expecting a promise to be returned. Does each await allow Rascal to get another message off the queue?

No - they are regular [node event handlers](https://nodejs.org/api/events.html), which are not awaited. However, setting the prefetch to 1 means that RabbitMQ will only permit one unacknowledged message per subscription so providing the code in the event handler awaits properly, and acknowledge the message at the end of the workflow, RabbitMQ will not delivery messages concurrently to the same subscription.

> We currently ackOrNack based on error or success at the end. The email was sent (1000's of times). After we fixed the misconfigured email template everything straightened it self out.

It's a common problem with explicit acknowledgements. You can use the redelivery counter previously mentioned to limit the number of retries, or use RabbitMQ's redelivered flag, or switch to quorum queues, or acknowledge just before sending the email. I prefer the latter option in cases where the user can request a resend (e.g. password reset / verification code). Even for order confirmations there's often a link to view previous order.

> In really it seems to be get message A await process, get message B await process, get message C await process, get message D await process... store offset B, store offset C, Store offset A, store offset D. Is the expected behaviour because of the connection pool? If so, do you have any suggestion for handling the offset tracking?

The connection pool is only used for publishing. As mentioned above, Rascal subscription uses a dedicated channel, so if you have configured the prefetch correctly, the RabbitMQ broker will only permit one unacknowledged message per subscription, and your desired workflow of

1. Get message A
2. Await process 
3. Store offset A
4. Acknowledge message A
5. Get message B
6. ...

is what you should see. If you are not awaiting all synchronous operations, have defined multiple subscriptions or have multiple instances of the container then you would see messages being interleaved. You can check whether a consumer has the correct prefetch configuration by looking in the management ui or through wireshark (you'll see a prefetch operation being sent from the client to the broker)

**Comment by cressie176** [comment]
Any luck @thaoula?

**Comment by thaoula** [comment]
We are still working though some issues and we have not been able to deploy a new version to the customer yet.

**Comment by cressie176** [comment]
I'm going to close for now, as there's nothing to suggest this is a problem with Rascal. Feel free to update if you continue to have issues though.

**Comment by thaoula** [comment]
Hi @cressie176,

I apologize, for not responding in a timely manner.

Just wondering, do you provide any consulting around RabbitMQ and Rascal?

Regard,
Tarek

**Comment by cressie176** [comment]
Hi @thaoula,
I've messaged you via linkedin.

**Comment by cressie176** [comment]
I added a [streams](https://github.com/onebeyond/rascal?tab=readme-ov-file#streams) section to the readme and also a streams based [example](https://github.com/onebeyond/rascal/tree/master/examples/streams)
